Repository betagouv/mon-profil-anssi, pull requests merged in 2024-12, with the labels that each got.

#2 Mets en place la configuration clever
  package-lock.json
  package.json
  scripts/clever-cloud/post-build-clever.sh
  src/index.ts
  src/serveur.ts
Labels: CI/CD

#7 [CORRECTION] Aseptise le header `x-id-client` avant de le sauvegarder
  src/api/ressourceInscription.ts
  tests/api/ressourceInscription.spec.ts
Labels: bug

#5 Utilise la route plutôt qu’un paramètre pour l’email
  src/api/ressourceProfil.ts
  tests/api/ressourceProfil.spec.ts
Labels: enhancement

#8 Mets à jour le profil lors d'une inscription ultérieure
  src/api/ressourceInscription.ts
  src/metier/erreurDonneesObligatoiresManquantes.ts
  src/metier/organisation.ts
  src/metier/profil.ts
  tests/api/ressourceInscription.spec.ts
  tests/api/ressourceProfil.spec.ts
  tests/metier/profil.spec.ts
Labels: enhancement

#9 Interdis la mise à jour vide de l’organisation et des domaines de spécialite
  src/api/ressourceInscription.ts
  src/metier/profil.ts
  tests/api/ressourceInscription.spec.ts
Labels: enhancement

#13 Ajoute à la configuration Docker un réseau pour les services du Lab
  README.md
  docker-compose.yml
Labels: enhancement, CI/CD

#12 Securise la ressource profil
  src/api/ressourceProfil.ts
  tests/api/ressourceProfil.spec.ts
Labels: enhancement
